baseURL = "https://thisland.netlify.app/"
title = "Thisland"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 10
summaryLength = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
