[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Archive"
  pageRef = "/posts/"
  weight = 20

[[main]]
  name = "About"
  pageRef = "/about/"
  weight = 30

[[main]]
  name = "Source"
  url = "https://github.com/LongMenJuZhen/thisland"
  weight = 40
